#spring:
#  datasource:
#    url: jdbc:mysql://localhost/rush?autoReconnect=true&useSSL=false&characterEncoding=utf-8
#    username: root
#    password: Lq.365
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true