package com.buy.rush.dao;

import com.buy.rush.dataObject.UserInfoDo;

public interface UserInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 13 17:31:19 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 13 17:31:19 CST 2020
     */
    int insert(UserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 13 17:31:19 CST 2020
     */
    int insertSelective(UserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 13 17:31:19 CST 2020
     */
    UserInfoDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 13 17:31:19 CST 2020
     */
    int updateByPrimaryKeySelective(UserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Apr 13 17:31:19 CST 2020
     */
    int updateByPrimaryKey(UserInfoDo record);
}